services:

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: docker-demo-api

    ports:
      - "8080:8080"
      
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=demodb;Username=demo;Password=demo123"

  postgres:
    image: postgres:18
    container_name: docker-demo-postgres

    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo123
      POSTGRES_DB: demodb

    ports:
      - "5432:5432"